### PR TITLE
Update .travis.yml PostgreSQL version to 10

### PR DESCRIPTION
**Pull request by carbonin**
Update .travis.yml PostgreSQL version to 10

### CODE REVIEW

**Comment by carbonin** [comment]
@miq-bot assign @gtanzillo 

@gtanzillo can you take a look at this one. Not sure why specs don't look like they're running here though ...

**Comment by carbonin** [comment]
@gtanzillo @Fryguy ping. Looks like all the PRs on this repo are updates to the .travis.yml

**Comment by gtanzillo** [comment]
@carbonin IIRC, we disabled the tests on this repo because they were intermittently failing and we have no plans to use this code in ManageIQ going forward

**Comment by carbonin** [comment]
Okay, so should I close this and maybe we can then discuss archiving the repo? Or do you just want to merge all of these so they're not sitting around?

**Pull request merged**
