### PR TITLE
Make rails engines zeitwerk autoloader friendly 

### PR DESCRIPTION
**Pull request by jrafanie**
* Rename constants that aren't really acronyms to avoid having to specify this manually
* Use the namespaced `lib/manageiq/consumption.rb` instead of `lib/manageiq-consumption.rb` as the former is zeitwerk friendly and both are acceptable for bundler

Note, this is an attempt to minimize the changes in the engine but more changes may be needed when we drop the old loader and switch to zeitwerk.  This change should be mergeable today without changing to zeitwerk and is an example of what I'll be doing in other engines.

### CODE REVIEW

**Comment by jrafanie** [comment]
cc @agrare

**Comment by Fryguy** [comment]
Asid, but semi-related, do we even "use" this in the core app - we've wanted to remove this repo for a while, and theres a small subset that's actually used that we should move to the core repo.

**Comment by jrafanie** [comment]
> Asid, but semi-related, do we even "use" this in the core app - we've wanted to remove this repo for a while, and theres a small subset that's actually used that we should move to the core repo.

yup, I can see it used here:

```ruby
app/models/chargeback.rb:      plan = ManageIQ::Showback::PricePlan.find_or_create_by(:description => rate.description,
app/models/chargeback_rate_detail.rb:    showback_rate = ManageIQ::Showback::Rate.find_or_create_by(:entity      => entity,
spec/models/chargeback_configured_system_spec.rb:    ManageIQ::Showback::InputMeasure.seed
spec/models/chargeback_container_project_spec.rb:    ManageIQ::Showback::InputMeasure.seed
spec/models/chargeback_vm_spec.rb:    ManageIQ::Showback::InputMeasure.seed
```

I'd love to remove it or the unused parts but I'm just not very confident in how it works to do it.

**Comment by jrafanie** [comment]
Note, if we go the route of eager loading with zeitwerk, there are two additional changes we can do later on:

```diff
diff --git a/lib/manageiq/consumption.rb b/lib/manageiq/consumption.rb
index b0823f2..3e0a410 100644
--- a/lib/manageiq/consumption.rb
+++ b/lib/manageiq/consumption.rb
@@ -1,2 +1,5 @@
 require "manageiq/showback/engine"
 require "manageiq/showback/version"
+
+module ManageIQ::Consumption
+end
diff --git a/lib/manageiq/showback/engine.rb b/lib/manageiq/showback/engine.rb
index 34dcbbb..dd804ef 100644
--- a/lib/manageiq/showback/engine.rb
+++ b/lib/manageiq/showback/engine.rb
@@ -6,6 +6,7 @@ module ManageIQ
       isolate_namespace ManageIQ::Showback

       config.autoload_paths << root.join('lib').to_s
+      config.eager_load_paths << root.join('lib').to_s

       def self.vmdb_plugin?
         true
```

**Comment by jrafanie** [comment]
This is ready for review/merge.

**Comment by kbrock** [comment]
fun: `bin/console` had `require "manageiq/consumption"`
it is as if they knew

**Pull request merged**
