### PR TITLE
Bump master travis.yml to ruby 2.3.8.

### PR DESCRIPTION
**Pull request by jrafanie**
Bump master travis.yml to ruby 2.3.8.

### CODE REVIEW

**Comment by jrafanie** [comment]
@miq-bot add_label gaprindashvili/yes
@miq-bot add_label hammer/yes

**Comment by simaishi** [comment]
@jrafanie This repo didn't get bump to 2.4.4...  I see https://github.com/ManageIQ/manageiq-consumption/pull/139 got closed by bot without merge!  Since 2.4.5 is coming soon, I guess that will take care of 2.4.x update...

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 2bd09336e075ff43895f6c47496123f8b8624912
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Dec 14 14:51:50 2018 -0500

    Merge pull request #146 from jrafanie/master_bump_travis_to_238
    
    Bump master travis.yml to ruby 2.3.8.
    
    (cherry picked from commit 8332a92532774a6c0065e595e9143d92205b233a)
```

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 793d5990cf5eb8a4ca05d4c52c7d28eaec995ab1
Author: Jason Frey <fryguy9@gmail.com>
Date:   Fri Dec 14 14:51:50 2018 -0500

    Merge pull request #146 from jrafanie/master_bump_travis_to_238
    
    Bump master travis.yml to ruby 2.3.8.
    
    (cherry picked from commit 8332a92532774a6c0065e595e9143d92205b233a)
```

**Pull request merged**
