### PR TITLE
Migration to Showback

### PR DESCRIPTION
**Pull request by aljesusg**
This changes are for remove Consumption name by Showback. This don't break core repo travis.

### CODE REVIEW

**Comment by aljesusg** [comment]
@chargio, @gtanzillo  maybe we can remove now all consumption* and merge together with https://github.com/ManageIQ/manageiq/pull/16337 instead make the migration in 2 steps. What do you think?

**Comment by chargio** [comment]
@gtanzillo Do we want Gaprisdanvhili/yes? I know is not important, but to have the code aligned with the future before we release the first release

**Comment by gtanzillo** [comment]
@chargio 
>@gtanzillo Do we want Gaprisdanvhili/yes? I know is not important, but to have the code aligned with the future before we release the first release

I agree that we do want this backported to gaprindashvili to keep it aligned. It will avoid a lot of confusion later.

@aljesusg Let's keep this PR separate from ManageIQ/manageiq#16337. I think combining them will make the PR too big.

**Comment by aljesusg** [comment]
Roger @gtanzillo I'll make the changes again and we'll go step by step

**Review by chargio — APPROVED** [review]
LGTM

**Comment by chargio** [comment]
Coverage will increase when we finish the migration, deleting the old files

**Pull request merged**
